return {}
-- return {
--   "kndndrj/nvim-dbee",
--   dependencies = {
--     "MunifTanjim/nui.nvim",
--   },
--   build = function()
--     -- Install tries to automatically detect the install method.
--     -- if it fails, try calling it with one of these parameters:
--     --    "curl", "wget", "bitsadmin", "go"
--     require("dbee").install()
--   end,
--   opts = function()
--     return {
--       sources = {
--         require("dbee.sources").MemorySource:new({
--           { name = "HW", type = "mysql", url = "mysql://root:root@localhost:5432" },
--         }),
--       },
--     }
--   end,
--   config = function(_, opts)
--     require("dbee").setup(opts)
--   end,
--   keys = function()
--     local dbee = require("dbee")
--     return {
--       {
--         "<leader>dt",
--         dbee.toggle,
--         desc = "Toggle DB UI",
--       },
--     }
--   end,
-- }
