require("mouarius.plugins-setup")
require("mouarius.core.options")
require("mouarius.core.keymaps")
require("mouarius.core.colorscheme")

-- plugins
require("mouarius.plugins.comment")
require("mouarius.plugins.markdown-preview")
require("mouarius.plugins.nvim-tree")
require("mouarius.plugins.lualine")
require("mouarius.plugins.telescope")
require("mouarius.plugins.nvim-cmp")
require("mouarius.plugins.lsp.mason")
require("mouarius.plugins.lsp.lspsaga")
require("mouarius.plugins.lsp.lspconfig")
require("mouarius.plugins.lsp.null-ls")
require("mouarius.plugins.autopairs")
require("mouarius.plugins.treesitter")
require("mouarius.plugins.gitsigns")
